# Generated by Django 3.2 on 2021-04-29 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_remove_application_experience'),
        ('userprofile', '0005_auto_20210426_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='application',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='conversationmessages', to='job.application'),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
