# Generated by Django 3.2 on 2021-04-29 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_remove_application_experience'),
        ('userprofile', '0006_auto_20210429_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='job',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='conversationmessages', to='job.job'),
        ),
    ]
