# Generated by Django 3.2 on 2021-05-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_alter_conversationmessage_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='application',
        ),
    ]
