# Generated by Django 3.2 on 2021-04-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20210427_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='short_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='company_size',
            new_name='to',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_country',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_place',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_zipcode',
        ),
        migrations.RemoveField(
            model_name='job',
            name='long_description',
        ),
    ]
